services:
  postgres:
    image: postgres:15-alpine
    container_name: black-pages-db
    environment:
      POSTGRES_DB: black_pages
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d black_pages"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build: .
    container_name: black-pages-migrate
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/black_pages?sslmode=disable
    command: ["./migrate", "up"]
    restart: "no"

  app:
    build: .
    container_name: black-pages-app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/black_pages?sslmode=disable
      - JWT_SECRET=your-secret-key-change-in-production
      - PORT=8080
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data: